### PR TITLE
Makes the test suite green.

### PR DESCRIPTION
**Pull request by sbleon**
Thanks for this gem! It's been really helpful in my current project.

### CODE REVIEW

**Comment by sbleon** [comment]
@npflood can you please take a look at this and my other PRs? I think you'll find them easy to review. I'm hoping you can get a new release out soon that incorporates my fixes.

If this gem is actually unmaintained, would you be open to giving me write access to it?

**Comment by npflood** [comment]
@sbleon I'm reviewing this now, sorry it took so long to get back to you I've been traveling more frequently and the nature of our organization takes me off the grid. I'm excited you're putting in pull requests. Love to know how you're using this.

**Comment by sbleon** [comment]
Thanks, @npflood! Can you also add me and a couple of my colleagues as
authors http://guides.rubygems.org/command-reference/#gem-owner on
rubygems.org? Our emails are:

leon@singlebrook.com
codingcyborg@gmail.com
jared@jaredbeck.com

Once that’s done I can make a new release of the gem :-)

**Comment by sbleon** [comment]
Oh, one more request. Please either make me an admin on these repos or give @rodel30 and @jaredbeck write access. Thanks!

**Comment by npflood** [comment]
@sbleon I'm sorry I've been away and missed your last two messages. You are now an admin on this repo as I have clearly not given it the attention it needs.

**Comment by npflood** [comment]
You are now an admin on both repos and I added you and the others you requested as owners on the gems. Let me know if I missed any steps.

**Pull request merged**
